explore:
  robot_base_frame: summit_xl_base_link
  costmap_topic: /summit_xl/move_base/global_costmap/costmap
  costmap_updates_topic: /summit_xl/move_base/global_costmap/costmap_updates
  visualize: true
  planner_frequency: 0.25
  progress_timeout: 30.0
  potential_scale: 3.0
  orientation_scale: 0.0
  gain_scale: 1.0
  transform_tolerance: 0.3
  min_frontier_size: 0.75
